name: semantic-release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'malaporte/nopecode'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: ./.github/actions/setup-bun

      - name: Install dependencies
        run: bun install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bun run node_modules/.bin/semantic-release --repository-url https://x-access-token:${GITHUB_TOKEN}@github.com/malaporte/nopecode.git
